### ISSUE TITLE
Resolve broken links in each MD file

### ISSUE THREAD

**Issue by patrickryan79** [DNNCommunity/DNNDocs#13]
Open issue and instructions for reformatting the individual markdown pages that are related to the warnings about broken links when building. 

There are two primary issues that need to be resolved for each markdown file.

1. Images that currently exist in a sub-folder for a particular topic need to be moved to the main `images` folder in the root
2. The `toc` at the top of the file needs to be removed and sub-headings need to be added instead which build the sidebar menu.

See https://github.com/DNNCommunity/dnn-docs/commit/f8f7fa06f31178d6f00d31ea76782f2edef6b617

**Comment by CBPSC** [comment]
All links have been updated to XREF's and there shouldn't be any more broken links. If you find any please mention me in the post and I'll investigate.

**Comment by dnndev** [comment]
We can safely close this issue.
