### ISSUE TITLE
Indicate specific editions to which each article applies

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/DNNDocs#136]
## Description of problem
Some features in the docs are Evoq specific such as the ["Site Groups" feature](https://dnndocs.com/content/administrators/sites/create-site-group/index.html), but the reader currently doesn't have a way of knowing that.

## Description of solution
Create some UI banner, denotation, icon, or callout that let's the user know that the feature is Evoq specific.

## Description of alternatives considered
Open to alternatives

## Screenshots
N/A

## Additional context
N/A

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by nvisionative** [comment]
I have an idea for this one.  @CBPSC I see this one is assigned to you.  Are you working on a solution or is this something I can tackle?  I am thinking of something like this...

<img width="1192" alt="Screenshot 2019-04-14 00 42 57" src="https://user-images.githubusercontent.com/4568451/56088417-53543b80-5e4e-11e9-973b-674be18e1ea5.png">

**Comment by nvisionative** [comment]
Perhaps this would provide more clarity to the reader:
<img width="712" alt="Screenshot 2019-04-14 00 53 15" src="https://user-images.githubusercontent.com/4568451/56088480-babebb00-5e4f-11e9-9c06-d459651a7bdc.png">

**Comment by dnndev** [comment]
I think using logos in this manner are a bit too visually distracting. Plus the logos, because they are composed differently, are jarring to the eye. My preference would be to replace the logos and the white bar & border with simple text:

**Applies to:** DNN Platform, Evoq Content, Evoq Engage

This line could go directly below the date/time to read/contributors line and above the horizontal rule or it could go below the horizontal rule.

**Comment by nvisionative** [comment]
@dnndev thanks for the feedback.  Could I potentially convince you to meet in the middle somewhere for improved UX (perhaps still using the bar to distinguish the purpose/section?  Placing it below the **date / time to read / contributors** line (but above the bottom border) will probably look okay on desktop but it will fall apart on mobile.  Placing it below the border will cause it to just blend in with the article content.  However, I suppose we could do some special styling of the text to set it apart.

**Comment by nvisionative** [comment]
Based on the above feedback and dialog on Slack, here is what I propose:
<img width="1230" alt="Screenshot 2019-04-14 14 18 47" src="https://user-images.githubusercontent.com/4568451/56097297-4839f380-5ec0-11e9-835f-61fc28013ed3.png">

**Comment by nvisionative** [comment]
Per our Slack conversation, we are going with this look and feel.  Thanks for the great feedback!

<img width="1229" alt="Screenshot 2019-04-14 14 28 46" src="https://user-images.githubusercontent.com/4568451/56097634-15462e80-5ec5-11e9-9225-dafdaa9ddc38.png">
