### ISSUE TITLE
Improve the "Improve this Doc" link

### ISSUE THREAD

**Issue by nvisionative** [DNNCommunity/DNNDocs#154]
## Description of problem
Currently, the "Improve this Doc" feature on the DNNDocs site is just a plain hyperlink.  This makes it a bit difficult to find.  This should be a stronger Call to Action (CTA).

## Description of solution
Apply button styling to the "Improve this Doc" hyperlink.

## Description of alternatives considered
n/a

### Current Look & Feel
![ScreenCapture_ 2019-03-29 04 56 PM _2212](https://user-images.githubusercontent.com/4568451/55262250-98b81c80-5243-11e9-9b4a-38fd477d67bd.jpg)

### Proposed Look & Feel
**Normal State:**
<img width="156" alt="Screenshot 2019-03-28 20 13 11" src="https://user-images.githubusercontent.com/4568451/55262104-26dfd300-5243-11e9-8886-9fcb1387534f.png">

**On Hover State:**
<img width="166" alt="Screenshot 2019-03-28 20 13 21" src="https://user-images.githubusercontent.com/4568451/55262115-2f380e00-5243-11e9-9d2a-fb97e009b0bd.png">

## Additional context
The DNNDocs DocFx implementation contains Bootstrap, so Bootstrap styling of `btn btn-primary` should be used.  However, the current vendor CSS colors need to be updated to reflect the site color scheme.

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by patrickryan79** [comment]
Looks nice @nvisionative, but do we want to make it stand out that much? I would go for switching the two states so that it's solid when hovered over. Just a thought. I'm good either way and definitely looks better than what's currently there.

**Comment by nvisionative** [comment]
@patrickryan79 thanks for the comments.  How about this...

**Normal State:**
![ScreenCapture_ 2019-03-29 05 26 PM _2214](https://user-images.githubusercontent.com/4568451/55263602-efbff080-5247-11e9-88ab-f86fbdf59dee.jpg)

**On Hover State:**
![ScreenCapture_ 2019-03-29 05 26 PM _2215](https://user-images.githubusercontent.com/4568451/55263609-f484a480-5247-11e9-9fdb-4090edcfbafc.jpg)

This would be a bit less "in your face".  This uses `btn btn-default`.

**Comment by patrickryan79** [comment]
@nvisionative I like it sir!

**Comment by dnndev** [comment]
Looks good @nvisionative

**Comment by nvisionative** [comment]
Thanks for the quick feedback @patrickryan79 and @dnndev - I'll get this implemented.

**Comment by perezandres** [comment]
I think that "Improve this doc" link should open in new tab, by using "target='_blank'". Now if you click the link, you're taken out of dnndocs.com
I'm not sure if this is the place to suggest this, or if I should open a new issue ;-)

**Comment by dnndev** [comment]
Thanks @perezandres for the suggestion. This should be a new issue so we can track it and get it resolved.

**Comment by perezandres** [comment]
OK, let's do it ;-)
