### ISSUE TITLE
Minimum DNN Version

### ISSUE THREAD

**Issue by dnndev** [DNNCommunity/DNNDocs#165]
## Description of problem
It would be helpful for readers to know at a glance if a topic applies to their version of DNN. This allows them to understand if the content can be used for their site.

## Description of solution
Place the minimum DNN version to which the topic applies near the top of each page. Placing the _minimum_ version allows content within the topic to specify alternative versions for particular topics. As a fairly extreme example, if a topic covers the UserInfo entity and a "WearsTophat" property was added in DNN 10, then the page header would reflect DNN 3 as the minimum version (or the first version the UserInfo appeared in) and the "WearsTopHat" portion of the page could be marked with "Added in Version 10".

**Comment by david-poindexter** [comment]
At some point along the way, this was implemented as the `firstappearedinversion` header attribute.  See [THIS PAGE](https://docs.dnncommunity.org/content/features/security-privacy/privacy/cookie-consent/index.html#cookie-consent) for an in-use example.  Below is an example of the YAML header for this page.

```
---
uid: cookie-consent
locale: en
title: Cookie Consent
dnnversion: 09.03.01
firstappearedinversion: 09.03.00
---
```

We'll go ahead and close this issue.  Thanks!
