### ISSUE TITLE
Add Feedback Feature

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/DNNDocs#172]
It would be great if we could get a simple form at the bottom of each docs page to allow anonymous users to submit feedback on the docs content. This would be following MSFT's style.

## Description of problem
The problem attempting to be solved here is the scenario where a user simply wants to provide feedback on a DNN Docs page with as little resistance/lowest barrier of entry as possible. That is they don't want to submit a pull request, touch/look at/or think about code, and optionally they may not have a GitHub user account.

## Description of solution
At the bottom of each page put an H1 with the title "Feedback" and allow the user to enter a title and a message, then click submit. This content would then create an issue on GitHub that the DNN Docs team could then review and act on or close. 

It would be similar to clicking the "Content Feedback" on any docs.microsoft page as shown below. Here's a [live link to a sample page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio).

## Description of alternatives considered
I don't know of any other alternatives

## Screenshots
![Feedbax](https://user-images.githubusercontent.com/4571863/55360900-aff54500-54a3-11e9-974e-2690024ca626.jpg)

## Additional context
N/A

**Comment by nvisionative** [comment]
Per a DNN Docs core team meeting today, our initial pass at this feature will be an action, similar to **Improve this Doc**, in the breadcrumb bar for **Feedback**.  The action will send a **title** and/or **body** as querystring parameters to a URL for creating a new **Issue** in the DNN Docs GitHub repo.

Here is an example based on Microsoft docs:

### Documentation Page
[Docs > .NET > .NET Guide > .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
`https://docs.microsoft.com/en-us/dotnet/standard/net-standard`

### Feedback URL
`https://github.com/dotnet/docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%209eb8b774-c6f0-8235-6964-15219baf2ea7%0A*%20Version%20Independent%20ID%3A%206819a4a7-7527-d8c7-e132-767f7344e00e%0A*%20Content%3A%20%5B.NET%20Standard%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Fstandard%2Fnet-standard)%0A*%20Content%20Source%3A%20%5Bdocs%2Fstandard%2Fnet-standard.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fblob%2Fmaster%2Fdocs%2Fstandard%2Fnet-standard.md)%0A*%20Product%3A%20**dotnet**%0A*%20Technology%3A%20**dotnet-standard**%0A*%20GitHub%20Login%3A%20%40mairaw%0A*%20Microsoft%20Alias%3A%20**mairaw**`

### Resulting New Issue on GitHub Repo
<img width="1003" alt="Screenshot 2019-04-17 19 41 41" src="https://user-images.githubusercontent.com/4568451/56327570-e4762b80-6148-11e9-8822-0e1ca5974191.png">

Obviously, Microsoft is passing a lot of information in the issue **body** that serves deeper integration/linking with other systems.  We do not intend to go to this level at this point, but rather ease into this type of feature by simply passing a simple **title** "starter" and a "template" of sorts for the **body** with, at minimum, the URL to the DNN Docs page from which the **Feedback** action was initiated.
