### ISSUE TITLE
Restyle the footer and replace DocFx info with something meaningful to the DNN Community

### ISSUE THREAD

**Issue by nvisionative** [DNNCommunity/DNNDocs#173]
## Description of problem
The current footer section is out-of-the-box DocFx styling and messaging.  This needs to be updated to reflect the style of the DNNDocs website, and the messaging needs to be more meaningful to the DNN Community.

## Description of solution
Update styling and messaging to reflect **Option 1** below.

## Description of alternatives considered
**Option 2** and **Option 3**

## Screenshots
**Option 1**
<img width="1680" alt="Screenshot 2019-04-01 17 05 59" src="https://user-images.githubusercontent.com/4568451/55361739-2004ca80-54a6-11e9-90f7-d90573614c46.png">

**Option 2**
<img width="1680" alt="Screenshot 2019-04-01 17 07 34" src="https://user-images.githubusercontent.com/4568451/55361740-2004ca80-54a6-11e9-9464-d5cd5f4c5e28.png">

**Option 3**
<img width="1679" alt="Screenshot 2019-04-01 17 32 31" src="https://user-images.githubusercontent.com/4568451/55361741-2004ca80-54a6-11e9-81a0-d02f03ca1e7e.png">

## Additional context
This will require a change to the custom DocFx theme for DNNDocs.

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by dnndev** [comment]
+1 for Option 1
