### ISSUE TITLE
Add support for PDF downloads for each article

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/DNNDocs#175]
## Description of problem
There is currently no way to download a PDF for each article and it would be really nice to have this feature (similar to what is seen on the Microsoft Docs site - see below screenshot - bottom left below sidebar).

## Description of solution
Add a PDF download option for each article.

## Description of alternatives considered
n/a

## Screenshots
<img width="1625" alt="Screenshot 2019-04-01 18 37 57" src="https://user-images.githubusercontent.com/4568451/55364089-509c3280-54ad-11e9-9343-7a0a9ff05c5a.png">

## Additional context
n/a

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by dnndev** [comment]
This is built-in to DocFX. We just need to enable it if I recall correctly.
