### ISSUE TITLE
"In This Article" Links Are Truncated

### ISSUE THREAD

**Issue by dnndev** [DNNCommunity/DNNDocs#177]
## Description of bug
The in-page navigation sidebar "In this Article" contains links to major sections within each topic. If those section titles are too long, they are truncated rather than wrapping to a new line (see attached image)

## Steps to reproduce
1. Navigate to http://localhost:8080/content/developers/extensions/dnn-manifest-schema/index.html
2. See 'friendlyName and descriptio' in the "In This Article" sidebar

## Current result
In the above example, `description` is truncated to `descriptio`. 

## Expected result
The page should display the full section title `friendlyName and description`

## Screenshots
![2019-04-01_16-55-20](https://user-images.githubusercontent.com/1757808/55366933-af5aaf80-549f-11e9-9c72-62c62d56b5b0.png)

**Comment by nvisionative** [comment]
@dnndev I found the issue - for whatever silly reason, there is a `margin-right: -20px;` on that list.  I'll submit a PR and get this fixed.  Thanks for reporting it!
