### ISSUE TITLE
"Improve this Doc" to be opened in new tab

### ISSUE THREAD

**Issue by perezandres** [DNNCommunity/DNNDocs#195]
## Description of problem
I think that "Improve this doc" link should open in new tab, by using "target='_blank'". Now if you click the link, you're taken out of dnndocs.com

**Comment by nvisionative** [comment]
@perezandres thank you for reporting this concern and idea for improvement.  We are actually working to improve the overall user experience a bit in this area and your ideas will indeed be taken into consideration.
