### ISSUE TITLE
Restructure Docs File/Folder Hierarchy to Match TOC 

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/DNNDocs#198]
## Description of documentation change
The current file/folder structure of the docs project is close to the actual structure of the content, but there are several instances where they do not align. This is especially true for the areas where category or "placeholder" folders were created to make the TOC function as it should. From the end-user's perspective this may not matter too much as they will not be aware, but for maintainers and/or contributors this will reduce confusion and make things "live" where they should.

## Existing documentation URL (if applicable)
n/a

## Existing documentation section (if applicable)
multiple sections would be changed 

## Proposed area for new documentation (if applicable)
The proposed "fix" for this would not require any content creation or deletion, but rather restructuring the hierarchical order of some files and folders. This means the moving folders inside of other folders so that the file/folder structure makes sense and aligns with the organization and structure found in the TOC.

**Comment by nvisionative** [comment]
I agree with a restructuring of folders to match TOCs.

**Comment by CBPSC** [comment]
From what I can tell this task has been complete as much as it possibly can be at this point.  The structure doesn't match exactly, but as discussed in the DNN Docs meeting it's ok to have a few straggler files. I think this issue may be ok to close at this point in time.
