### ISSUE TITLE
Update Persona Bar Images to show Platform UI vs. Evoq

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/DNNDocs#199]
## Description of documentation change
Currently every image of the persona bar shows the Evoq UI. This is already causing confusion for platform developers who think they are in the wrong area. The images should be changed out to platform for the areas where the documentation is directly referencing content that applies to the platform.

## Existing documentation URL (if applicable)
Example page [Create Standard Page](https://dnndocs.com/content/administrators/pages-templates/create-single-page-standard/index.html)

## Existing documentation section (if applicable)
There are several

## Proposed area for new documentation (if applicable)
All of them! Just replacing PB images by overwriting the existing files

## Screenshots
![PB-Compare](https://user-images.githubusercontent.com/4571863/55756460-9a41cb80-5a1f-11e9-9885-df5c2988dd57.png)

.

**Comment by nvisionative** [comment]
Re-opening this issue as it was accidentally closed via auto-close syntax in #200

**Comment by david-poindexter** [comment]
@CBPSC can this issue be closed now, or are there more to update?

**Comment by david-poindexter** [comment]
In an effort to clean up our issue backlog, I am closing this issue.  This was a very broad issue and at this point can be handled via more granular/specific issues.  Thanks to @CBPSC for kick-starting this effort!
