### ISSUE TITLE
Decrease top margin for main content and right sidebar

### ISSUE THREAD

**Issue by nvisionative** [DNNCommunity/DNNDocs#232]
## Description of problem
Currently, there is too much top margin about the main article content area and the right sidebar area.

## Description of solution
Decrease top margin above main article content area and the right sidebar area.

## Description of alternatives considered
n/a

### Current
<img width="1289" alt="Screenshot 2019-04-13 23 41 25" src="https://user-images.githubusercontent.com/4568451/56088032-0ff5cf00-5e46-11e9-9702-7cf3281c63c2.png">

### Proposed
<img width="1301" alt="Screenshot 2019-04-13 23 41 49" src="https://user-images.githubusercontent.com/4568451/56088041-1e43eb00-5e46-11e9-889b-520de6418bb6.png">

## Additional context
n/a

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by dnndev** [comment]
I think we also need to add a little top margin above the filter box in the left sidebar
