### ISSUE TITLE
What is DNN section

### ISSUE THREAD

**Issue by jncraig** [DNNCommunity/DNNDocs#271]
## Description of documentation change
I've been sort of underwhelmed by the "What is DNN?"section.  The link goes to a detailed description of some things that are important, but don't even attempt to answer the question.

## Existing documentation URL (if applicable)
Provide URL to existing documentation.

## Existing documentation section (if applicable)
What is DNN?
[What is DNN.docx]

## Proposed area for new documentation (if applicable)
Provide the area in which the proposed new documentation should reside.

## Screenshots
If applicable, provide screenshots to help explain your documentation request.

## Additional context
Here is an outline with some notes.

[What is DNN.docx](https://github.com/DNNCommunity/DNNDocs/files/3095113/What.is.DNN.docx)

I could use some pointers on how to get this in motion ...

**Comment by dnndev** [comment]
Hi @jncraig. Thanks for your contribution. We agree the "What is DNN?" section needs to be revamped. We'll take a look at what you've provided and get back to you soon.

**Comment by CBPSC** [comment]
Hey @jncraig thanks for getting this started. Let's work to get this into a place to where it's "submittable" as a pull request! 

I've created a Google Doc where this document can be worked on collaboratively, in real time. I've added some comments and content as next steps.

https://docs.google.com/document/d/1HeZ4CyVH_IXfpDuppR16kYtnsVh2HFOBn6K4J_XlAG0/edit?usp=sharing

Once we get it all shined up you can submit a PR with it. Also, feel free to share the link with others.

**Comment by jncraig** [comment]
I have Requested Access to the document.

**Comment by CBPSC** [comment]
Sorry about that... just updated the permissions settings to give you edit access.

**Comment by dnndev** [comment]
Any update on this content?

**Comment by david-poindexter** [comment]
Closing this issue per recent contributions by @donker to this section (now in **Features** > **General**).  Thank you Peter!
