### ISSUE TITLE
Feedback for DNN API Documentation Home

### ISSUE THREAD

**Issue by liffeyd** [DNNCommunity/DNNDocs#283]
Search at the top right of the page works as expected. However if I go to the API page and enter the same search term in the "Enter filter here" box no results are returned.

To reproduce:
Enter "modulepath" in search box in blue bar. A number of results are returned. Entering the same term in the filter box returns no results.

---
#### Document Details

⚠ *Do not edit this section. It is required for dnndocs.com ➟ Core Team processing.*

* Content Source: [undefined](https://github.com/DNNCommunity/DNNDocs/blob/master/api/index.md/#L1)

**Comment by CBPSC** [comment]
I believe the search in the blue nav menu at the top is the global site search whereas the filter on the left-hand column is filtering the items in the Table of Contents that are listed just below the filter. Let's see if @dnndev or @nvisionative can confirm that notion.

**Comment by liffeyd** [comment]
"modulepath" exists in DesktopModulePath in DotNetNuke.Common/Globals so, IMHO, "modulepath" as a filter should match.

Perhaps filtering the table of contents is the intended behaviour but this is not what I would expect.

**Comment by dnndev** [comment]
That's correct - the filter box on top of the table of contents is intended to filter the table of contents. This is the built-in behavior for docfx. If it is unclear, perhaps a different label would be appropriate. Suggestions are welcome.

**Comment by dnndev** [comment]
"Filter" seems to be an appropriate label for the box at this time. Since no alternatives have been offered, I'm closing this issue. We can re-open if it's deemed necessary.
