### ISSUE TITLE
Add DNN Releases Archives

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/DNNDocs#287]
## Description of documentation change
Currently, there are no references in the docs to the official [DNN Releases Archives on GitHub](https://github.com/dnnsoftware?utf8=%E2%9C%93&q=archive&type=&language=).  These need to be included.

## Existing documentation URL (if applicable)
n/a

## Existing documentation section (if applicable)
n/a

## Proposed area for new documentation (if applicable)
Not quite sure, but will give this some thought.

## Screenshots
n/a

## Additional context
Currently, these repos are hard to find even though we have blogged about them, promoted via DNN meetups, social media posts/responses, forums, etc.

**Comment by hismightiness** [comment]
When implemented, I believe that the IMPORTANT call out should be used to tell people to not install older versions of DNN.

https://dnndocs.com/content/contribute/docs/markdown-guide-to-docfx/index.html#using-callouts-in-docs

**Comment by dnndev** [comment]
These are linked from the product releases page with all other versions. The Codeplex text needs to change to GitHub. I have an open issue #255 to expand the release list to versions less than 7.0

**Comment by valadas** [comment]
Also I have just updated the old wiki suggested upgrade path links to the archives, if that is moved into the docs project (would be nice) then I think this is enough as we don't want to recommend installing the old version unless it is in the context of steps to upgrade to the current release.

**Comment by Tychodewaard** [comment]
I think this issue can be closed? https://dnndocs.com/content/reference/releases/index.html 
And the suggested upgrade paths are also on https://dnndocs.com/content/getting-started/setup/upgrades/suggested-upgrade-path/index.html

**Comment by david-poindexter** [comment]
@Tychodewaard no - this issue is for the [Archive repos](https://github.com/dnnsoftware?utf8=%E2%9C%93&q=archive&type=&language=).  That said, I have it on my to do list to update the Releases you referenced to point to the archives for releases prior to the move from CodePlex to GitHub.

**Comment by valadas** [comment]
Given that we don't want to promote installing old versions and we have appropriate links in the suggested upgrade path, do we still need to do this?

**Comment by david-poindexter** [comment]
@valadas this is not about promotion as much as it is about making the archives more accessible to those that need to find them (for whatever reason - yes, there are still valid use cases for these be that right, wrong, indifferent).  😉

**Comment by valadas** [comment]
Cool, cool

**Comment by david-poindexter** [comment]
Fyi...I updated Reference > Releases today to update all versions back to 7.0.0.
