### ISSUE TITLE
Identify DNN Docs as Official Documentation Site in Homepage SERP

### ISSUE THREAD

**Issue by dnndev** [DNNCommunity/DNNDocs#318]
If a user searches for "dnn docs" in Google, they see numerous listings, including the home page for DNN Docs at position 3 and 4 (as of this writing). It is confusing for the user, trying to determine which is the real, official documentation site. See image below
![image](https://user-images.githubusercontent.com/1757808/60203704-0f909180-9802-11e9-9a38-8d3bf00b79cf.png)

Change the Title and meta Description tags to reflect that DNN Docs is the official documentation site for DNN Platform.

**Comment by valadas** [comment]
And if the 2 first urls could have a permanent redirect to the official docs, then the official one would get to the first result :)
