### ISSUE TITLE
RFC: How to Avoid Shared Content Context Shift?

### ISSUE THREAD

**Issue by dnndev** [DNNCommunity/DNNDocs#32]
When linking to common content, the user is taken out of their "section" of the docs. This causes a context shift and confusion for the user. 

For example, Developers who click on "Set Up DNN" are taken to the common setup information inside "Administrators".  There is no way for them to get back to their previous page and they may not even be aware they are in a new section.

**Comment by dnndev** [comment]
Can we inject ourselves into build process to copy common content to appropriate sections.

Will a breadcrumb help?

**Comment by CBPSC** [comment]
For the user's experience it may be best to copy the common content to each section.

I also think a breadcrumb will be help in general to helping users understand where they are in the tree of documentation.

**Comment by dnndev** [comment]
Looks like DocFX has a mechanism to include content from one .md file into another using markdown link syntax: https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#links-in-file-includes

We can use this to create a container page for, say, Glossary, in Admin and a Glossary contain in Developer (etc) and each container page would contain an include to a common file with the glossary content.

**Comment by dnndev** [comment]
I've demonstrated how to do the includes using DocFX in commit e0b7dec
