### ISSUE TITLE
Add how to upgrade Dnn

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNNDocs#344]
## Description of documentation change
It would be nice to add the procedure to follow to upgrade Dnn and the suggested upgrade path in the docs.
Explaining how to backup the database, backup the site files, then show the suggested upgrade path and the couple gotchas with some upgrades.

## Existing documentation URL (if applicable)
https://www.dnnsoftware.com/wiki/suggested-upgrade-path

## Proposed area for new documentation (if applicable)
Install/Upgrade section

**Comment by hismightiness** [comment]
Is this assigned to me because you want me to add it?  :D

**Comment by CBPSC** [comment]
Yes, and you were voted to do it in today's meeting that you just skipped. #YouWelcome

**Comment by hismightiness** [comment]
🙄 😛

**Comment by hismightiness** [comment]
I stopped maintaining that years ago!  😆
