### ISSUE TITLE
Resolve broken links

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/DNNDocs#348]
## Description of bug
There are 8 broken links found when the website is scanned using brokenlinkcheck.com.  :)

(There are actually more reported depending on the scanner you use, but they appear to be duplicates.)

Text:  Version History
Page:  https://dnndocs.com/
Bad URL:  https://dnndocs.com/content/guides/tutorials/product-versions/index.html
Correct URL:  https://dnndocs.com/content/administrators/product-versions/index.html

Text:  Creating Themes
Page:  https://dnndocs.com/
Bad URL:  https://dnndocs.com/content/guides/tutorials/creating-themes
Correct URL:  https://dnndocs.com/content/guides/tutorials/creating-themes/designers-creating-themes-overview/index.html

Text:  Community Managers
Page:  https://dnndocs.com/content/guides/tutorials/dnn-overview/index.html
Bad URL:  https://dnndocs.com/content/community-managers/
Correct URL:  (no relevant page exists)

Text:  Look through the DNN-Connect directory
Page:  https://dnndocs.com/content/guides/tutorials/extensions/developers-extensions-overview/index.html
Bad URL:  https://www.dnn-connect.org/community/community-extensions
Correct URL:  https://dnncommunity.org/forge

Text:  Improve this Doc
Page:  https://dnndocs.com/content/administrators/
Bad URL:  https://github.com/DNNCommunity/DNNDocs/blob/master/content/administrators/index.md/#L1
Correct URL:  https://github.com/DNNCommunity/DNNDocs/blob/master/content/guides/tutorials/administrators-overview/index.md/#L1  (_???_)

Text:  Improve this Doc
Page:  https://dnndocs.com/content/developers/
Bad URL:  https://github.com/DNNCommunity/DNNDocs/blob/master/content/developers/index.md/#L1
Correct URL:  https://github.com/DNNCommunity/DNNDocs/blob/master/content/guides/tutorials/developers-overview/index.md/#L1  (_???_)

Text:  Improve this Doc
Page:  https://dnndocs.com/content/designers/
Bad URL:  https://github.com/DNNCommunity/DNNDocs/blob/master/content/designers/index.md/#L1
Correct URL:  https://github.com/DNNCommunity/DNNDocs/blob/master/content/guides/tutorials/designers-overview/index.md/#L1  (_???_)

Text:  Improve this Doc
Page:  https://dnndocs.com/content/content-managers/
Bad URL:  https://github.com/DNNCommunity/DNNDocs/blob/master/content/content-managers/index.md/
Correct URL:  https://github.com/DNNCommunity/DNNDocs/blob/master/content/guides/tutorials/content-managers-extensions-overview/index.md/#L1  (_???_)

## Additional context
I can do the PR, but I'd first like confirmation on the "Improve this Doc" links above.  :) 

## Affected browser

* [x] All

**Comment by hismightiness** [comment]
As mentioned in PR #349 I believe that the "Improve this Doc" links should probably be resolved in a separate issue and PR.  :)

**Comment by david-poindexter** [comment]
@hismightiness recently we made a massive IA change to this project.  This resulted in a new file/folder structure for conceptual files under `/content`.  These paths are no longer persona driven.  Therefore, some of the "Correct URL" links listed about are in fact not correct anymore.  

A link scanner will most likely detect files within the output site directory `_site`.  I think we will need @dnndev to check the Jenkins and/or hosting environment to ensure a "clean up" has been done for the output site files.  Most likely, we have rogue files left over from previous builds.  Hopefully, the Jenkins build can be setup to "clean" the output directory prior to `docfx build` moving forward.

**Comment by hismightiness** [comment]
I didn't scan the `_site` folder. I ran this on the production website. This is a reflection of those results, not dev.

**Comment by david-poindexter** [comment]
@hismightiness by scanning dnndocs.com you are in essence scanning the static site output from DocFx, which is the `_site` folder.  Sorry for any confusion.  We are working on this.

**Comment by dnndev** [comment]
As a result of the IA change, a lot of content was moved to a different physical location and that caused some broken links we didn't catch. Some are just bad links that should be fixed :) 

However, some of the "correct" links aren't actually correct. They used to resolve because there were some old files left over in the site. For instance, https://dnndocs.com/content/administrators/product-versions/index.html. After cleaning up the site, removing the old files, links like this should now result in a 404.  

For those files that still exist, we should fix the URLs on the broken links. There are some broken links identified that point to content that no longer exists -- the content was removed, usually because it was evoq specific (Community Managers-related content for example).

I'll start working through this list and making the corrections.

**Comment by david-poindexter** [comment]
@dnndev - @hismightiness already has a PR going (#349) and I'm sure he would probably like to see that one all the way through to merge.  I'd recommend picking up the conversation there if need be and let Will push additional commits as necessary to get the non "Improve this Doc" issues resolved.

**Comment by dnndev** [comment]
I've made my comments/suggestions on #349

**Comment by hismightiness** [comment]
Merged by Kelly just now.  :)
