### ISSUE TITLE
Feedback for Site Aliases

### ISSUE THREAD

**Issue by Paul-Morris** [DNNCommunity/DNNDocs#353]
I'm very confused as to why I need a site alias or what it is for. Are they the same as an alias in in Drupal? (basically an SEO friendly url to the content?)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for dnndocs.com ➟ Core Team processing.*

* Content Source: [site-aliases](https://github.com/DNNCommunity/DNNDocs/blob/master/content/guides/tutorials/configuring-your-site/site-aliases/index.md/#L1)

**Comment by hismightiness** [comment]
Hello @Paul-Morris 

That's a great question.  I've just submitted a PR to get this updated in the documentation.  In the meantime, here's the description that's submitted for approval...

-------------------------------------------------------------------------------------

# Site Aliases  
In DNN, it's possible for you to specify more than one domain name for your website to respond to.  For example, `domain1.com` and `domain2.com` could potentially be the same website. The site alias feature allows you to do easily this by simply adding the new/alternate domain name or URL.  These additional domain names might function in a redirect or canonical fashion.  It's up to you.  

There are many other ways to leverage the site alias feature as well.  This is a feature that also is used to help migrate websites during rebranding, development, staging, and testing.  For instance, you may have a production website at `example.com`, but using this feature you could restore the production website in a staging environment and change the primary site alias to be `dev.example.com`.

**Comment by Paul-Morris** [comment]
Nice! That clears it up. I was really stuck on the Drupal definition of an alias which is basically a seo friendly url for any piece of content on the site

--
Paul Morris
(647) 456-7285

**Comment by hismightiness** [comment]
My pleasure, @Paul-Morris .  I completely understand and am happy to help.  We all tend to use multiple platforms these days, and the "lingo" can sometimes be part of the learning curve.  :)

Also, welcome to the DNN community!  :)  Don't forget to join us on the official community website.

https://dnncommunity.org

**Comment by Paul-Morris** [comment]
Thanks will do!
