### ISSUE TITLE
Fully document SPA tokens

### ISSUE THREAD

**Issue by dnndev** [DNNCommunity/DNNDocs#362]
## Description of documentation change
Fully document the SPA tokens.  This blog provides most of the tokens but does not document key items like the _provider_ attribute of the `[JavaScript...]` token with the valid values for the attribute or an example of its usage.

https://www.dnnsoftware.com/community-blog/cid/155247/module-development-in-dnn-8-5--new-tokens-to-support-building-pure-spa-modules

Docs Reference: https://dnndocs.com/content/guides/tutorials/modules/about-modules/spa-module-development/index.html

**Comment by valadas** [comment]
When working on this, it is important to note that in order to be able to use the request verification token using `[ValidateAntiForgeryToken]` in API controllers, one must also request the token in the SPA module html. And this must be done with the value True as such `[AntiForgeryToke:True]`
