### ISSUE TITLE
Repo's README Being Rendered into Website

### ISSUE THREAD

**Issue by dnndev** [DNNCommunity/DNNDocs#382]
## Description of bug
The git repository has a README.md file describing the contents of the repository and describing how to work with the repo. Since DocFX converts markdown files to HTML files when generating the website, it is creating a README.html page in the production site.

## Steps to reproduce
1. Go to [https://dnndocs.com/README.html](https://dnndocs.com/README.html)

## Current result
The content of the README.md file is displayed as an HTML page

## Expected result
The user should receive a 404 error because the page should not exist.

**Comment by david-poindexter** [comment]
@dnndev is it all that bad that this file is generated as an HTML file on the site?  To my knowledge, it is not linked to from anywhere else on the site.  So, one would have to know the URL to get to it.  Or perhaps they would get to it from indexed search results.  Even in that case, I don't see any real harm in the content.  Do you?

**Comment by david-poindexter** [comment]
Since this issue is still open and labeled as a bug, I'll go ahead and submit a PR to "fix" it.  ;-)
