### ISSUE TITLE
How to work with the User and Search UI Skin Objects

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNNDocs#388]
## Description of documentation change
A guide to help learn how to work with objects like the Account Messages Notifications UI and Search to make things such as badges appear using bootstrap and other FUN and interesting examples you can do working with themes.

For example if I would like to put everything on a carat next to the account profile image that shows messages, and make the search icon a button that expands underneath along with a hamburger menu item for the menu all on the same row with my icon.  Does dnndocs.com explain to me how I can accomplish this?  This should be a big part of wishing to dive into a new CMS is to see examples of how you are going to modify look and feel out of the box.

Unless I am missing something here it looks like this is a very untouched subject.

## Proposed area for new documentation (if applicable)
https://dnndocs.com/content/features/themes/index.html

## Screenshots
If applicable, provide screenshots to help explain your documentation request.
![image](https://user-images.githubusercontent.com/13577556/68331044-1d480480-0089-11ea-9db7-bcb2d46726e3.png)

## Additional context
Each part of a theme (Skin and Container) that can be edited needs a home in DNNDocs.  Tutorials and examples can then be used to help explain.  It would be even more fun to see the community contribute to this collection of information to help out finding answers and new solutions.

**Comment by david-poindexter** [comment]
@thabaum thanks for reporting the issue.  Some documentation already exists for [theme objects](https://dnndocs.com/content/tutorials/themes/theme-objects/index.html).  However, the idea is to clean up this list and expand documentation for each theme object, as you will already see for the [DDR Menu](https://dnndocs.com/content/tutorials/themes/theme-objects/ddrmenu/index.html) in that list.  This is one of the many areas I'd personally love to see more documented too!  😉 

The first task should probably be to "clean up" the list.  That should be documented as an issue by itself.  I have this one on my "wish list" but I just haven't gotten around to it yet.  Is this one you'd like to take on?  If so, you can use [THIS FILE](https://github.com/nvisionative/nvQuickTheme/blob/master/partials/_registers.ascx) as a starting point for a full and accurate list of all currently available theme objects.  That's where I was going to start.

Beyond that, some of the more advanced wishes you stated would probably be great content for the **Labs** section.

In an effort to keep our backlog of issues clear and actionable, I am going to close this issue, but feel free to follow up with more narrow-focused issues and/or pull requests.  Thanks!
