### ISSUE TITLE
Document the new glob support for cleanup component in manifest

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNNDocs#422]
## Description of documentation change
I am working on a PR to add support for globing patterns in the manifest cleanup component, this new feature needs to be documented.

## Existing documentation URL (if applicable)
None, but I am writing it now and will submit a PR for it.

## Existing documentation section (if applicable)
https://dnndocs.com/content/tutorials/extensions/dnn-manifest-schema/index.html#the-dnn-manifest-schema

## Proposed area for new documentation (if applicable)
It is a complement to existing documentation

## Additional context
I am working on this and will submit both PRs soon...

**Comment by david-poindexter** [comment]
Fantastic- thank you @valadas!

**Comment by valadas** [comment]
Go to bed you...
