### ISSUE TITLE
Duplicate Content in Admin Micro-Services

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/DNNDocs#46]
In the Administrators section we have some duplicate content and I believe it may be this way across all "personas" index pages in the docs project.

`Administrators > Microservices > About Micro-Services` 

 has the same content as 

`Administrators > MicroServices > Administrators-Microservices-Overview`

**Comment by dnndev** [comment]
@CBPSC has this been resolved yet or is it still active?

**Comment by david-poindexter** [comment]
This issue appears to no longer exist.  Closing in an effort to clean up our issue backlog.
