### ISSUE TITLE
Correct CSS Load Order

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNNDocs#463]
## Description of documentation change
Is your documentation request related to existing documentation or new documentation? Provide a clear and concise description of the requested documentation change.

The load order of CSS files in the DNN platform does not mention Page.css, Admin.css, or DefaultPriorty CSS file load orders.

## Existing documentation URL (if applicable)
Provide URL to existing documentation.

## Existing documentation section (if applicable)
Provide the name of the documentation section to be changed.

## Proposed area for new documentation (if applicable)
Provide the area in which the proposed new documentation should reside.

I have a pull request to submit with what I feel should be documented.
## Screenshots
If applicable, provide screenshots to help explain your documentation request.

## Additional context
Add any other context about the documentation request that may be helpful with implementation.

A skin or module developer could possibly use defaultpriority which could throw someone off that does not understand why CSS styles are not taking affect in Portal.css

Page.css everyone expects to have highest priority or load last but it loads first which can also throw a dnn user or developer off.

**Comment by valadas** [comment]
This is done right, should it be closed?

**Comment by dnndev** [comment]
This was merged in 30a497c
