### ISSUE TITLE
Feedback for DNN Replacement Tokens

### ISSUE THREAD

**Issue by renderfarmer** [DNNCommunity/DNNDocs#479]
I think this one is missing here: [Portal:PortalAlias]

---
#### Document Details

⚠ *Do not edit this section. It is required for dnndocs.com ➟ Core Team processing.*

* Content Source: [replacement-tokens](https://github.com/DNNCommunity/DNNDocs/blob/master/content/tutorials/references/replacement-tokens/index.md/#L1)

**Comment by david-poindexter** [comment]
@renderfarmer thanks for the feedback!  I just tested that token in DNN 9.5.0 and got the following:
```
Error accessing [Portal:PortalAlias], PortalAlias is unknown for datasource Portal.
```
I believe it was formerly supported does not seem to work now.  I am not sure if this is a bug or intentional.  I'll ask around and see what I can find out.

**Comment by renderfarmer** [comment]
Oh ok. I was wondering since it was in the old Documentation.

**Comment by david-poindexter** [comment]
@renderfarmer it looks like two new tokens were added though:

- one for `[Portal:Url]`
- and one for `[Portal:FullUrl]`

I'll go ahead and update the documentation to include those.  Thanks!

**Comment by renderfarmer** [comment]
Ok great.

**Comment by sleupold** [comment]
AFAIR. up to DNN 5 (when we implemented TokenReplace) , site aliases were stored as comma separated list in portalSettings table, SettingName PortalAlias. Later versions use a dedicated table. This might be the reason for the rename.
