### ISSUE TITLE
Feedback for DNN Platform Security

### ISSUE THREAD

**Issue by moorecreative** [DNNCommunity/DNNDocs#483]
Should this be re-titled something different than "Security" ? I refer to these things as "Roles & Permissions" I think of something different when thinking of the title "Security"

---
#### Document Details

⚠ *Do not edit this section. It is required for dnndocs.com ➟ Core Team processing.*

* Content Source: [platform-overview-security](https://github.com/DNNCommunity/DNNDocs/blob/master/content/features/security-privacy/security/index.md/#L1)

**Comment by david-poindexter** [comment]
@moorecreative this follows the same paradigm as has always been used in these areas within DNN.  As such, I think we'll leave this as is.  Thanks for the recommendation and participation!  🎉
