### ISSUE TITLE
Updade suggested upgrade path to minimize maintenance

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNNDocs#497]
## Description of documentation change
As discussed in slack, we now release much more often than before and updating the suggested upgrade path is something we would need to do very often. We discussed changing the last row to "latest 9.x.x release" and point that to the general release page.

## Existing documentation URL (if applicable)
https://dnndocs.com/content/getting-started/setup/upgrades/suggested-upgrade-path/index.html#dnn-platform-suggested-upgrade-path

## Additional context
I will submit a PR for that in a few minutes...

**Comment by david-poindexter** [comment]
@valadas thanks, but I am not sure this is the right approach.  The point here is to be explicit and link to the correct releases.

**Comment by valadas** [comment]
@david-poindexter Oh, I though that was a good idea from the slack discussion. Well the PR is in, I let you guys decide what you want to do. It's just that we forget often to update that section... I won't be mad if it get's closed, just an idea...

**Comment by david-poindexter** [comment]
Awesome - thanks for the contribution!  It may be a great idea, but I'll defer to consensus by the DNN Docs core team for this one instead of making the call in a silo here.  😉 
cc: @dnndev @donker @CBPSC @patrickryan79

**Comment by valadas** [comment]
@david-poindexter Sounds good, the PR is there to decide, I defer to whatever is decided.

**Comment by david-poindexter** [comment]
I think it is safe to close this one now.  Thanks again @valadas
