### ISSUE TITLE
Feedback for DNN Platform Upgrades

### ISSUE THREAD

**Issue by Trigger113** [DNNCommunity/DNNDocs#518]
I'm having trouble finding the minimum requirements (.net and IIS) to support each DNN release. Could this be listed here? My servers supports up to .net 4.5, and I don't know which version I need to stop at in the upgrade path. I'm upgrading from 6.2.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for dnndocs.com ➟ Core Team processing.*

* Content Source: [setup-upgrades](https://github.com/DNNCommunity/DNNDocs/blob/master/content/getting-started/setup/upgrades/index.md/#L1)

**Comment by david-poindexter** [comment]
@Trigger113 thanks for the issue submission.  

Requirements are documented [HERE](https://dnndocs.com/content/getting-started/setup/requirements/index.html).  

Links each release are documented [HERE](https://dnndocs.com/content/reference/releases/index.html).  Within the release notes, you will see any specific .NET Framework specific requirement changes.

Off the top of my head, I believe 9.4.0 bumped up the minimum requirement to .NET Framework 4.7.2.

While this is not a support forum, I will tell you that the server should be upgraded to 4.7.2 at a minimum and the DNN instance should be upgraded to 9.6.1 (and then 9.7.0 as soon as it is released).  It is always best practice to be on the latest release of DNN.  To my knowledge, there are no limitations from a server perspective on running 4.5.x versus 4.7.2+.  If you are in a shared hosting environment, then just open a support ticket and ask the hosting provider to make sure your server has 4.7.2+ installed.  

I am going to go ahead and close out this issue, but let us know if you run into any more issues with dnndocs.com.
