### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by jncraig** [DNNCommunity/DNNDocs#552]
## Description of bug
Dead links reported in the community forums.

## Steps to reproduce
List the steps to reproduce the behavior:

https://dnncommunity.org/forums/aft/1826#5582

There is a dead link on this page https://dnncommunity.org/Extensibility for No. 2 in the orderd list.The link points to https://dnndocs.com/content/feature...index.html  but I think it should reference https://dnndocs.com/content/feature...index.html

## Current result
links should work

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error
Paste the error that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by david-poindexter** [comment]
@jncraig it looks like this has been resolved on the DNN Community site.  I just confirmed the link works.  Thanks!

**Comment by jncraig** [comment]
Great!
