### ISSUE TITLE
Unable to see full list of methods in sidebar tree view

### ISSUE THREAD

**Issue by parasdaryanani** [DNNCommunity/DNNDocs#553]
## Description of bug
When browsing through API docs, specifically methods inside a class, the full list of methods is not visible in the sidebar. Scrolling does not work to reveal the list either, 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to the [UserController Class on DNNDocs.com](https://dnndocs.com/api/DotNetNuke.Entities.Users.UserController.html#DotNetNuke_Entities_Users_UserController)
2. Click on 'Methods' in the sidebar
3. Try scrolling past `CreateUser(ref UserInfo, Boolean)`
4. Notice that it doesn't let you.

## Current result
Methods that follow after `CreateUser(ref UserInfo, Boolean)` are not visible in the right hand sidebar, and scrolling down in the list does not work. The same behaviour is observed across all classes in the docs.

## Expected result
The full list of methods should be visible by scrolling down in the right hand sidebar.

**Comment by valadas** [comment]
I can scroll past it, is there other things that may be affecting this ?

- Which browser
- Does it happen in incognito mode to rule out any browser extension ?

**Comment by valadas** [comment]
oh, the right pane, ok, sorry

**Comment by parasdaryanani** [comment]
Yes, apologies, bug report update to explicitly state right hand sidebar. :)
