### ISSUE TITLE
How to include more assemblies in reference docs?

### ISSUE THREAD

**Issue by bdukes** [DNNCommunity/DNNDocs#557]
## Description of documentation change
The reference docs appear to only include docs from `DotNetNuke.dll`.  It would be helpful to include docs from many other assemblies (probably every assembly that's shipped as a NuGet package).  What would it take to include these other assemblies in the documentation?

Thanks!

**Comment by david-poindexter** [comment]
@bdukes it has been a long long time since I have looked into that piece, but I am pretty sure it can be configured [in the docfx.json file](https://github.com/DNNCommunity/DNNDocs/blob/master/docfx.json).

**Comment by dnndev** [comment]
As I recall you need to reference the project file in `docfx.json` -- in the `metadata` section.
