### ISSUE TITLE
Feedback for DNN Platform Telerik Removal

### ISSUE THREAD

**Issue by Orrouk** [DNNCommunity/DNNDocs#573]
[Enter feedback here]
Everything worked perfectly. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for dnndocs.com ➟ Core Team processing.*

* Content Source: [setup-telerik-removal](https://github.com/DNNCommunity/DNNDocs/blob/master/content/getting-started/setup/telerik-removal/index.md/#L1)

**Comment by david-poindexter** [comment]
Awesomeness- thanks for the feedback!
