### ISSUE TITLE
Feedback for DNN Platform Telerik Removal

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/DNNDocs#578]
Shouldn't we also add the removal of the packages in \App_Data\ExtensionPackages ?

If so, I'll add that.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for dnndocs.com ➟ Core Team processing.*

* Content Source: [setup-telerik-removal](https://github.com/DNNCommunity/DNNDocs/blob/master/content/getting-started/setup/telerik-removal/index.md/#L1)

**Comment by hismightiness** [comment]
That's a great point...  I couldn't imagine needing those package(s) after removing it.  :)
