### ISSUE TITLE
Platform Requirements haven't been updated in a while

### ISSUE THREAD

**Issue by RichFinn-WTW** [DNNCommunity/DNNDocs#649]
## Description of documentation change
Please update documentation to reflect current DNN version. We're specifically curious about support for latest Windows, SQL, and VS versions

## Existing documentation URL (if applicable)
[DNN Platform Requirements](https://github.com/DNNCommunity/DNNDocs/blob/main/content/getting-started/setup/requirements/index.md)

**Comment by david-poindexter** [comment]
Thanks for pointing this out @RichFinn-WTW - I just submitted a PR for this.
