### ISSUE TITLE
Fix or Remove Skinning Tool Link in Glossary

### ISSUE THREAD

**Issue by dnndev** [DNNCommunity/DNNDocs#66]
https://github.com/DNNCommunity/DNNDocs/blob/master/content/administrators/glossary/index.md

A tip callout references 10 Pound Gorilla's Skinning Tool. This link does not point to the tool. It points to the 10 Pound Gorilla home page. This link should be corrected or removed if the tool no longer exists or is out of date.

**Comment by birksy89** [comment]
The tool exists here these days:
http://10poundgorilla.com/DNN-Skinning-Tool
