### ISSUE TITLE
Feedback for DNN Platform Telerik Removal

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/DNNDocs#670]
For a multi portal installation, I just uninstall the Digital Asset Manager and it's automatically removed from all pages. 
Why would you first delete the module from the pages it is placed on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.dnncommunity.org ➟ Core Team processing.*

* Content Source: [setup-telerik-removal](https://github.com/DNNCommunity/DNNDocs/blob/main/content/getting-started/setup/telerik-removal/index.md/#L1)

**Comment by valadas** [comment]
Yeah, there's that...
