### ISSUE TITLE
Feedback for Setting Up DNN

### ISSUE THREAD

**Issue by pieropetralla90** [DNNCommunity/DNNDocs#681]
"DNN Requirements" button doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.dnncommunity.org ➟ Core Team processing.*

* Content Source: [administrators-setup-overview](https://github.com/DNNCommunity/DNNDocs/blob/main/content/tutorials/server/setup/administrators-setup-overview/index.md/#L1)

**Comment by david-poindexter** [comment]
@pieropetralla90 thank you for reporting this bug.  I just submitted a PR to resolve the issue.
