### ISSUE TITLE
Feedback for DNN API Documentation Home

### ISSUE THREAD

**Issue by ericfsmith** [DNNCommunity/DNNDocs#685]
I cannot find the latest, or for that matter any, API documentation. I've noticed a conversation on Slack between @Paras Daryanani and @Daniel Valadas regarding the issue. I'm not sure how to proceed or suggest a fix.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.dnncommunity.org ➟ Core Team processing.*

* Content Source: [undefined](https://github.com/DNNCommunity/DNNDocs/blob/main/api/index.md/#L1)

**Comment by david-poindexter** [comment]
There is a known build issue - we just need time to look into it and resolve it.  Thanks for reporting this.

**Comment by iJungleboy** [comment]
@david-poindexter Any details about the cause? I also use docfx a lot, maybe I have an idea?

**Comment by david-poindexter** [comment]
@iJungleboy any help would be much appreciated - we believe it is a build issue but just haven't had time to dive deep into it.

**Comment by valadas** [comment]
Any help is welcome @iJungleboy if you have some time to look at it. Not sure how it broke, just did not have a minute to myself to take a deeper look yet.

**Comment by david-poindexter** [comment]
PR #689 unfortunately did not resolve the issue.  Still looking.

**Comment by valadas** [comment]
We did spend quite a few hours trying to solve this. The problem is not obvious... I assure you nobody here likes to have that not working. It's just volunteer work and it's a hard problem to figure out.

**Comment by david-poindexter** [comment]
This has now been resolved via #691 🎉 🌮

**Comment by iJungleboy** [comment]
This is wonderful!
Thanks guys so much.
What fixed it? for future reference...?

**Comment by david-poindexter** [comment]
> This is wonderful!
> 
> Thanks guys so much.
> 
> What fixed it? for future reference...?

Thanks - here's the PR that fixed it - #691
