### ISSUE TITLE
DNN API missing on docs website (empty!)

### ISSUE THREAD

**Issue by iJungleboy** [DNNCommunity/DNNDocs#686]
## Description of bug

The API page on references is empty!!!

![image](https://user-images.githubusercontent.com/5321186/202493626-60942226-abcd-4bb9-a53f-ecdfa2506e07.png)

## Steps to reproduce

Go to https://docs.dnncommunity.org/api/

**Comment by valadas** [comment]
Duplicates #685 we have a build issue we need to look at.
