### ISSUE TITLE
Stupid cms not works on Windows Server 2022

### ISSUE THREAD

**Issue by ednsinf** [DNNCommunity/DNNDocs#728]
Stupid cms not works on Windows Server 2022

0:02 Minutes   |   20% ERROR occured - Processing file (C:\inetpub\wwwroot\dnn\bin\DotNetNuke.Website.dll.config) Error: Access to 'C:\inetpub\wwwroot\dnn\bin\DotNetNuke.Website.dll.config' denied.

**Comment by david-poindexter** [comment]
If by "stupid cms" you are referring to DNN, it actually works just fine on Windows Server 2022.  

For the account that runs the ASP.NET worker process, you will need to grant MODIFY or FULL rights to the root of DNN and subfolders/files.  If you need further support, recommend posting on the [DNN Community Forums](https://dnncommunity.org/forums) where community members can help guide you through the process in greater detail.

**Comment by valadas** [comment]
Yeah, work totally fine on Windows Server 2022, you just have a permissions issue here...

**Comment by ednsinf** [comment]
Done and not works fix urgent

**Comment by valadas** [comment]
Sorry to be blunt but you have posted 16 forums messages without noticing that the forums are moderated and waiting for your post to be approved. I just spent about 15 minutes cleaning that up.

If you want, please do 1 new post explaining what you have tried so far and please be mindful on the language.
Then patiently wait for approval of your post.
Dnn is free, the docs a free and the forums are fee and maintained by volunteers like us that don't get paid to do so.
We are always happy to help but try to at least use a polite language.
