### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by ednsinf** [DNNCommunity/DNNDocs#729]
Permissions in folder are done and error not solves fix urgent

0:02 Minutes | 20% ERROR occured - Processing file (C:\inetpub\wwwroot\dnn\bin\DotNetNuke.Website.dll.config) Error: Access to 'C:\inetpub\wwwroot\dnn\bin\DotNetNuke.Website.dll.config' denied.

**Comment by david-poindexter** [comment]
This is not a support channel.  Please reach out to community members for help via the DNN Community website or the DNN Community Discord (link on HOME page of https://dnncommunity.org).
