### ISSUE TITLE
Update old URLs

### ISSUE THREAD

**Issue by bdukes** [DNNCommunity/DNNDocs#86]
In addition to the Codeplex URLs called out by #84, there are many other URLs that are pointed to old domains or pages.

For example, Bruce Chapman's site is offline, so we could use an archive.org URL to his blog posts.  The DNN Forge has been taken down, so references to that could be removed.  There are also some placeholder usages of google.com that can be removed.

**Comment by dnndev** [comment]
Resolves #84
