### ISSUE TITLE
RFC: Deployment Process

### ISSUE THREAD

**Issue by dnndev** [DNNCommunity/DNNDocs#9]
We need the following:

* A build server
* A temporary public-facing server to display results

I can run this with my Jenkins server and output it to an S3 site or my server as a static site. Thoughts?

**Comment by dnndev** [comment]
Jenkins is setup to publish the docs project. However, there is another issue. The project needs the DNN source code in order to build the source code docs as part of the overall build process. Of course, we do not want to include DNN.Platform source in the docs source. So we need to come up with a way to do a pull during each build.

**Comment by dnndev** [comment]
I have setup Jenkins to pull the source code as part of the build. The entire build now takes approx 5 minutes to complete currently.

**Comment by ohine** [comment]
@dnndev I’m happy to help get things configured on the sponsored azure account the platform uses. We already have all the connections to github, dnns source, and space available we could auto-deploy. Feel free to ping me if you’d like access or any help with that part of the process.

**Comment by dnndev** [comment]
Thanks @ohine. I appreciate the help.  We're getting closer to that point. The current setup works for us now, but I'll be sure to connect with you when we get further along.

**Comment by dnndev** [comment]
Closing this for now since we are using Jenkins during development. This can be revisited at a later date if circumstances change.

**Comment by harishgatla** [comment]
@dnndev i have an dnn9 website for which i would like to setup Jenkins build for continuous deployment. Could you please help me in this setup or could you send me some help documents if you have any.
Thanks in Advance.
